src/staticfiles/css/style.css
src/templates/main/base.html
src/templates/student/register.html

Icon color changed and css file changed accordingly 
- Code
- Documentation
- Test

icon color changed

---

requirements.txt
src/main/admin.py
src/main/models.py
src/main/views.py
src/templates/main/base.html
src/templates/main/mixins/recruiters_mixin.html

models.py :
Added PastRecruiters model where the logo of the company is uploaded to company-logo
admin.py - 
Registered PastRecruitersAdmin
views.py - 
modified companies in context 
recruiters_mixin.html -
Showed the companies logo if comapany logo uploaded else the name of the company is shown .
base.html -
Deleted commented out html 
requirements.txt - 
Added Pillow to requirements

Add ability to edit Past Recruiters through admin

---

src/main/admin.py
src/main/models.py
src/main/views.py
src/templates/main/index.html

models.py :
Added News Model.
fields: Title,Order_no,Active,Content,Document,File_title,Link,Link_title
admin.py :
Registered NewsAdmin.
views.py :
added news_list in context object.
index.html :
Showed all news from news_list.

Added ability to update News from Admin Panel.

---

src/main/admin.py
src/main/models.py
src/main/views.py
src/templates/main/index.html

Updated models.py, views.py , admin.py in main folder so that user can update testimonial through django admin.
models.py : made models for testimonial
views.py : added testimonial_list
admin.py : registered AlumniTestimonial
index.htm : linked front end data of testimonial through django admin 
-code

Update testimonial through django

---

src/accounts/forms.py
src/accounts/models.py
src/accounts/views.py
src/templates/company/register.html

Modified form.py, views.py and models.py of accounts app and register.html
- Code

Added Contact Field in Company Registration.

---

src/templates/main/contacts.html
src/templates/main/mixins/contact_card_mixin.html

UI for contact cards changed and made responsive with respect to large , medium , small screen sizes.
- Code

UI design of contact cards changed and made responsive

---

src/main/admin.py
src/main/models.py
src/main/views.py
src/templates/main/index.html

Added Homepage Carousel
- Code

Added Home Carousel.

---

src/spc_django/urls.py
src/templates/accounts/password_reset_email.html

password_reset_email.html - 
modified to send a html version of email
urls.py -
modified to render the email
- Code

Created html version of password reset email

---

src/templates/company/offer.html
src/templates/company/offers_list.html
src/templates/main/admissions.html
src/templates/main/summary.html
src/templates/student/offers_list.html
src/templates/student/resume.html

src/templates/company/offer.html
src/templates/company/offers_list.html
src/templates/main/admissions.html
src/templates/main/summary.html
src/templates/student/offers_list.html
src/templates/student/resume.html

Made tables Responsive and Scrollable

---

src/templates/main/mixins/contact_card_mixin.html

modified contact_card_mixin to show program_branch of core team contacts 
- Code

Shows the program branch of core team contacts

---

src/accounts/forms.py
src/accounts/models.py
src/accounts/views.py
src/spc_django/settings.py
src/templates/company/register.html
src/templates/student/register.html

Refactored Company and student registration forms and added image field in student registration form.
Modified accounts/forms.py, accounts/models.py, accounts/views.py, student/register.html, company/register.html
- Code

Refactored forms and added image field in student registration form.

---

.travis.yml
src/company/tests/test_urls.py
src/main/tests/test_urls.py
src/spc_django/tests.py
src/student/tests/test_urls.py

added tests for URLs in apps company, main, student and in spc_django.

Added tests for URLs.

---

src/accounts/forms.py
src/templates/student/register.html

Corrected Date of Birth field. Made last name and email field required.
- Code

Fix StudentRegistration Form errors of PR #22

---

.env.example
src/accounts/forms.py
src/accounts/models.py
src/spc_django/settings.py

Added a new email id for sending emails 
- Code

Changed the Email ID to send emails.

---

src/accounts/models.py
src/accounts/views.py

changed the position of calling of functions to send emails from accounts/models.py to accounts/views.py
- Code

changed the position of calling of functions to send emails from models to views

---

.env.example
src/spc_django/settings.py
src/student/forms.py
src/student/views.py
src/templates/student/details.html

Description
fixed issue with the details page and added a env variable to allow students to change GPA
- Code

Fixed issue with the details page and added a env variable to allow students to change GPA

---

requirements.txt
src/spc_django/settings.py

Include a summary of the change and relevant motivation/context.  
List any dependencies that are required for this change.
- Code

Removed duplicates.

---

src/main/urls.py

Corrected slug url.

---

src/main/urls.py

Added urls for tutorial pages in main/urls.py
- Code

Fixed Login Page

---

src/templates/student/base.html

Updated year verification for showing internship and job offers.
- Code

updated student year in login portal

---

src/templates/company/base.html
src/templates/company/joboffer_form.html
src/templates/main/base.html
src/templates/main/mixins/contact_card_mixin.html
src/templates/student/base.html
src/templates/student/details.html

Fixed after login pages UI.
- Code

Fixed after login pages UI.

---

src/spc_django/settings.py

Timezone changed.

---

src/templates/student/register.html

Updated student registration form.

Updated student registration form.

---

src/spc_django/urls.py

Change position main urls in spc_django/urls.py
- Code
- Documentation
- Test

fixed password reset link

---

src/main/context_processors.py
src/main/models.py

Order_no field added to nav bar options
- Code
- Documentation
- Test

Order_no field added to nav bar options

---

src/accounts/forms.py

Updated regex for student username
- Code

Updated regex for student username

---

.env.example
src/main/models.py
src/spc_django/settings.py
src/student/forms.py
src/templates/main/contacts.html
src/templates/student/details.html

Ability to control the update details page from env variable
- Code

Ability to control the update details page from env variable

---

src/templates/main/base.html
src/templates/main/index.html
src/templates/student/register.html

Changed about us and footer content

Changed about us and footer content

---

src/templates/student/base.html

New M.Tech roll numbers will be shown intern and job offers tab. And color changed from white to black so that it is visible in navbar
- Code

navbar compatibility of new m tech students

---

src/templates/company/base.html
src/templates/main/base.html
src/templates/student/base.html

Include a summary of the change and relevant motivation/context.  
List any dependencies that are required for this change.
- Code
- Documentation
- Test

Changed OSP to CDC in header and footer

---

src/templates/main/index.html

Updated brochure link.

---

src/templates/main/contact_main.html

Added a new contact us section.
- Code

Added a new contact us section.

---

src/templates/main/c3members.html

updated c3 members.

---

src/company/admin.py

Fixed error for '/' in company names and added warning for missing resumes.

Some bug fixes.

---

src/company/models.py

error fix for previously merged commit.

error fix.

---

src/accounts/forms.py
src/templates/student/register.html

Changed the username field label in the student registration form to adding roll number for login.
No additional dependencies required for this change.
Fixes #74
- Code

Changed form label

---

src/accounts/models.py
src/templates/accounts/company_details_email.html
src/templates/accounts/company_register_email.html
src/templates/accounts/password_reset_email.html
src/templates/accounts/password_reset_subject.txt
src/templates/accounts/student_register_email.html

The email sent to students and recruiters mentions SPC and Office of Student Placement, 
No additional dependencies required for this change.
Fixes #75 
changed email templates. now sent email mentions CDC and Career Development Cell.

changed SPC to CDC in email part

---

src/templates/main/base.html

resolved navbar mobile view issue #78
There is a vertical gap between heading and navbar
added internal CSS and some classes

Vertical gap between navbar and heading resolved

---

.env.example
src/accounts/models.py
src/accounts/views.py
src/spc_django/settings.py

Added a env variable to avoid automated emails during production
Fixes #73 
- Code
- Test

Set up env variables for Email

---

src/company/resources.py

changed csv export field. now  in csv export of intern/job advertisement export company column shows company name instead of PK of company.
- Code
- Bug fix 

changed csv export field

---

src/templates/student/register.html

I have updated norms for placements and internships.
- Code

updated norms for placements and internships.

---

src/main/models.py
src/templates/main/c3members.html
src/templates/main/contacts.html

added new designation for faculty incharge

Add faculty incharge designation

---

src/templates/main/c3members.html

Updated Dr. Kaushal Desai's designation to Associate Dean, International Relations & Outreach, Chairman
- Code

Updated designation for Dr. Kaushal Desai

---

src/templates/main/base.html

added logo of iitj in nav bar
- Code

added iitj logo

---

src/accounts/admin.py
src/accounts/resources.py

Added company person in resources so that the company export data also has company person data
- Code

added company person details in company data export

---

src/company/resources.py

Added UG gpa in Job/Intern offers export
- Code

Added UG gpa in Job/Intern offers export
